### PR TITLE
Feature exchange info multi target frameworks

### PR DESCRIPTION
**Pull request by BjornNordblom**
## Overview
Feature exchangeInfo.

## Solved Issues
Feature request, exchangeInfo. #18 

## Installation
N/A

## Acceptance and Testing Steps
- [x] Is it compatible for all target frameworks?

### CODE REVIEW

**Comment by BjornNordblom** [comment]
Some things addressed but not per your recommendations in previous PR:

1. BinanceException in converter. Since the types of ExchangeInfoSymbolFilter are now enums (part of the PR) JSON will throw a deserialization exception if the enum is not found. This is handled in the generic exception handler in APIProcessor.cs, which I think is cleaner. Reject if you feel otherwise :)

2. Not a shared or inherited "enum" (which would have to be a class instead) of OrderType/ExchangeInfoOrderType. ExchangeInfoOrderType is at least now its own enum.

**Comment by ryanjhardinorders** [comment]
@glitch100 
If this is working with no conflicts, can another release (e.g. 4.0.x) be quickly created/released that incorporates this enhancement? I'd like to take advantage of having access to a symbol's stepsize so I can place an order without it failing. I sure many others would also love to see this released on NuGet.

**Comment by glitch100** [comment]
@BjornNordblom @ryanjhardinorders  - I will release this with 4.2.0 (tonight or tomorrow) based on whether this is ready for merge

**Comment by glitch100** [comment]
Closed in favor of https://github.com/glitch100/BinanceDotNet/pull/24

**Pull request closed without merging**
